name: Sample Pipeline Job

on:
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Running a command
        run: |
          date
          echo "Build job completed"

  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Running a command from test
        run: |
          date
          echo "Test job completed"

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Running a command from deploy
        run: |
          date
          echo "Deploy job completed"
